
name: Deploy Java Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files for debugging
        run: ls -R  # This will list all directories and subdirectories

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: |
          cd path/to/git_batchdemo  # Update this path based on the output of the ls command
          mvn clean package

      - name: Upload WAR file
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: path/to/git_batchdemo/target/*.war  # Update path based on the directory structure

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download WAR file
        uses: actions/download-artifact@v3
        with:
          name: java-app
          path: target

      - name: Deploy WAR via SCP
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $HOSTNAME >> ~/.ssh/known_hosts
          scp -i ~/.ssh/id_rsa target/*.war ubuntu@${{ secrets.SSH_HOST }}:/home/ubuntu/

      - name: Copy WAR file to Tomcat webapps
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.SSH_HOST }} 'sudo cp /home/ubuntu/*.war /var/lib/tomcat9/webapps/'


